name: "Home Assistant Samsung the Frame changer"
description: "This Python script allows you to change your Samsung Frame's art based on a folder of images on your computer. The script picks an image from folder on your computer, then sends it to your TV and sets it as the active image automatically—it also does its best to try not repeatedly upload the same photo to your TV."
version: "0.25"
url: "https://github.com/gijsvdhoven/home-asssistant-samsung-frame-art"
slug: "hass-frame-changer"
init: false
startup: once
boot: manual
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - "media:rw"
options:
  tv: "192.168.1.199"
schema:
  tv: "str?"
labels:

  io.hass.name="Home Assistant Samsung the Frame changer for ${BUILD_ARCH}" 
  io.hass.description="Home Assistant Add-on: ${BUILD_ARCH} Home Assistant Samsung the Frame changer" 
  io.hass.arch="${BUILD_ARCH}" 
  io.hass.type="base" 
  io.hass.version=${BUILD_VERSION} 
  maintainer="Gijs van den Hoven" 
  org.opencontainers.image.title="Home Assistant Samsung the Frame changer for ${BUILD_ARCH}" 
  org.opencontainers.image.description="Home Assistant Community Add-on: ${BUILD_ARCH} Python base image" 
  org.opencontainers.image.vendor="Home Assistant Add-ons from Gijsvdhoven" 
  org.opencontainers.image.authors="Gijs van den Hoven" 
  org.opencontainers.image.licenses="MIT" 
  org.opencontainers.image.url="https://github.com/gijsvdhoven/homeassistant-addons" 
  org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" 
  org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/master/README.md" 
  org.opencontainers.image.created=${BUILD_DATE} 
  org.opencontainers.image.revision=${BUILD_REF} 
  org.opencontainers.image.version=${BUILD_VERSION}
